# Generated by Django 5.0.7 on 2026-09-28 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamLinkageEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('SHARED_SCAMMER_PHONE', 'Shared Scammer Phone'), ('SHARED_DESTINATION_ACCOUNT', 'Shared Destination Account'), ('TRANSACTION_HOP', 'Transaction Hop')], max_length=40)),
                ('shared_value', models.CharField(help_text='The phone number or account matched between reports.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='incidents.incidentreport')),
                ('target_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'forensics_scam_linkage_edge',
                'unique_together': {('source_report', 'target_report', 'edge_type', 'shared_value')},
            },
        ),
        migrations.CreateModel(
            name='TransactionLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_bank', models.CharField(max_length=100)),
                ('destination_bank', models.CharField(max_length=100)),
                ('destination_account', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('hop_level', models.PositiveIntegerField(default=0, help_text='0 = original transfer, 1+ = downstream hops.')),
                ('is_flagged_endpoint', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_hops', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'forensics_transaction_ledger',
                'ordering': ['hop_level', 'timestamp'],
                'indexes': [models.Index(fields=['destination_account'], name='forensics_t_destina_ca277e_idx'), models.Index(fields=['hop_level'], name='forensics_t_hop_lev_fd9193_idx')],
            },
        ),
    ]
