# Generated by Django 5.0.7 on 2026-09-28 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalExportPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investigative_notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='legal_exports/%Y/%m/')),
                ('package_hash_sha256', models.CharField(blank=True, help_text='Chain-of-custody integrity hash of the generated PDF.', max_length=64, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exports', to=settings.AUTH_USER_MODEL)),
                ('downloaded_by_police', models.ManyToManyField(blank=True, related_name='downloaded_exports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_exports', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_exports', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'audit_legal_export_package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAuditEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('response_time_ms', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_request_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActionAuditLog',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('target_report_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_entity', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.CharField(default='SUCCESS', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('payload_snapshot', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_action_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type', 'timestamp'], name='audit_actio_action__a3e594_idx')],
            },
        ),
    ]
