# Generated by Django 5.0.7 on 2026-09-28 20:04

import apps.incidents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_code', models.CharField(db_index=True, default=apps.incidents.models.generate_tracking_code, max_length=20, unique=True)),
                ('channel', models.CharField(choices=[('WEB', 'Web Portal'), ('TELEGRAM', 'Telegram Bot'), ('IVR', 'IVR Phone System')], max_length=20)),
                ('incident_type', models.CharField(choices=[('VOICE_SCAM', 'Voice Scam'), ('PHISHING', 'Phishing Link'), ('MOBILE_BANKING_FRAUD', 'Mobile Banking Fraud'), ('SMS_IMPERSONATION', 'SMS Impersonation'), ('SIM_SWAP', 'SIM Swap Fraud'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('scammer_phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('scammer_identifier', models.CharField(blank=True, help_text='Bank account, wallet, phishing domain, etc.', max_length=200, null=True)),
                ('risk_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('FROZEN', 'Frozen'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidents_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, help_text="Set for files uploaded through Django's own storage (web/Telegram intake).", null=True, upload_to='evidence/%Y/%m/')),
                ('external_url', models.URLField(blank=True, help_text="Set instead of `file` for evidence hosted on an external system (e.g. an IVR platform's own call-recording storage).", max_length=500, null=True)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image / Screenshot'), ('AUDIO', 'Audio Recording'), ('DOCUMENT', 'Document / Receipt'), ('OTHER', 'Other')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash_sha256', models.CharField(db_index=True, help_text='Integrity hash for chain-of-custody verification.', max_length=64)),
                ('ocr_parsed_json', models.JSONField(blank=True, null=True)),
                ('authenticity_flag', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('VALID', 'Valid'), ('FLAGGED', 'Flagged - Possible Tampering')], default='PENDING', max_length=20)),
                ('authenticity_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'incidents_evidence_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VictimProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fayda_id_hash', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victim_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidents_victim_profile',
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to='incidents.victimprofile'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['status', 'risk_score'], name='incidents_r_status_100328_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['incident_type'], name='incidents_r_inciden_52df87_idx'),
        ),
    ]
