# Generated by Django 5.0.7 on 2026-09-28 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFreezeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_bank_code', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed by Analyst'), ('APPROVED', 'Approved by Supervisor'), ('SENT', 'Sent to Bank/EthSwitch'), ('ACKNOWLEDGED', 'Acknowledged by Bank'), ('REJECTED', 'Rejected'), ('FAILED', 'Delivery Failed')], default='PROPOSED', max_length=20)),
                ('ethswitch_order_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_freezes', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_freezes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_orders', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'integrations_asset_freeze_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelecomEscalationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier', models.CharField(help_text='ETHIO_TELECOM or SAFARICOM_ET', max_length=30)),
                ('action_type', models.CharField(choices=[('SIM_SUSPEND', 'SIM Suspension'), ('IMEI_BLACKLIST', 'IMEI Blacklist')], max_length=20)),
                ('target_value', models.CharField(help_text='Phone number or IMEI', max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed by Analyst'), ('APPROVED', 'Approved by Supervisor'), ('SENT', 'Sent to Bank/EthSwitch'), ('ACKNOWLEDGED', 'Acknowledged by Bank'), ('REJECTED', 'Rejected'), ('FAILED', 'Delivery Failed')], default='PROPOSED', max_length=20)),
                ('carrier_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_telecom_orders', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_telecom_orders', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telecom_orders', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'integrations_telecom_escalation_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
